version: "4.8"

services:
  teachteam-mysql-db:
    image: mysql:8.0
    container_name: redis-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: adminday
      MYSQL_PASSWORD: adminday
      MYSQL_ROOT_HOST: "%"
